services:
  api-gateway-service:
    build:
      context: ./api-gateway-service
      dockerfile: Dockerfile
    image: api-gateway-service
    container_name: api-gateway-service
    ports:
      - "8080:8080"

  storage-gateway-service:
    build:
      context: ./storage-gateway-service
      dockerfile: Dockerfile
    image: storage-gateway-service
    container_name: storage-gateway-service
    expose:
      - "8080"
    env_file:
      - ./storage-gateway-service/.env.example
    depends_on:
      minio:
        condition: service_healthy

  task-manager-service:
    build:
      context: ./task-manager-service
      dockerfile: Dockerfile
    image: task-manager-service
    container_name: task-manager-service
    expose:
      - "8080"
    env_file:
      - ./task-manager-service/.env.example
    depends_on:
      minio:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
  task-dispatcher-service:
    build:
      context: ./task-dispatcher-service
      dockerfile: Dockerfile
    image: task-dispatcher-service
    container_name: task-dispatcher-service
    expose:
      - "8080"
    env_file:
      - ./task-dispatcher-service/.env.example
    depends_on:
      minio:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
  storage-notifications-service:
    build:
      context: ./storage-notifications-service
      dockerfile: Dockerfile
    image: storage-notifications-service
    container_name: storage-notifications-service
    expose:
      - "8080"
    env_file:
      - ./storage-notifications-service/.env.example
    depends_on:
      minio:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: tarantul
      MINIO_ROOT_PASSWORD: tarantul123
      MINIO_NOTIFY_WEBHOOK_ENABLE_PRIMARY: on
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_PRIMARY: http://storage-notifications-service:8080/webhook/
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  
  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: ["/bin/sh", "/init-minio.sh"]
    volumes:
      - ./minio-init/init-minio.sh:/init-minio.sh:ro

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: "/var/lib/kafka/data" 
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 10
  kafka-init:
    image: confluentinc/cp-kafka:latest
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKER: "kafka:9092"
    volumes:
      - ./kafka-init/init-kafka.sh:/kafka-init.sh:ro
    command: ["/bin/bash", "/kafka-init.sh"]
volumes:
  mongo-data:
  minio-storage:
  kafka-data: